### ISSUE TITLE
Problem with \colorbox when using in two instances of Tex2SVG

### ISSUE THREAD

**Issue by sbondaryev** [jpribyl/react-hook-mathjax#1]
Hello,
Thanks for your project!
I've just tried to use `\colorbox` with two instances - the rendering for` \colorbox` is not working 
Code example: 
```
<Tex2SVG display="inline" latex="\colorbox{aqua}{$test$}" />
<Tex2SVG display="inline" latex="\colorbox{aqua}{$test$}" />
```
It works fine if I use only one `Tex2SVG` instance.

**Comment by jpribyl** [comment]
@sbondaryev thanks for the issue! I will try to reproduce when I have a second - let me know if you discover anything new

**Comment by jpribyl** [comment]
@sbondaryev I was able to reproduce this issue. I tracked it down to `MathJax` failing to load the `color` package. It has to do with event bubbling.

At any rate, I have published a new version (2.0.4). In it, I have exposed the NAMED export `{ Tex2SVG }` unlike the DEFAULT export `Tex2SVG` the named export does not include a provider. 

This should allow you to create your own provider and give it some options. Take a look at the MathJax docs [here](http://docs.mathjax.org/en/latest/input/tex/extensions.html?highlight=colorbox#configuring-tex-extensions) for a hint on what you must make those options.

I would anticipate the final code to be something like this:
```typescript
import { Tex2SVG, MathJaxProvider } from 'react-hook-mathjax';

const mathjaxOptions = {
  loader: { load: ['[tex]/color'] },
  tex: { packages: { '[+]': ['color'] } },
};

const MyComponent: React.FC = () => (
  <MathJaxProvider options={mathjaxOptions}>
    Big <Tex2SVG display="inline" latex="O" /> notation
    <Tex2SVG display="inline" latex="\colorbox{aqua}{$test$}" />
    <Tex2SVG display="inline" latex="\colorbox{aqua}{$test$}" />
  </MathJaxProvider>
)
```

This worked for me:
![image](https://user-images.githubusercontent.com/27659352/101233821-dfe0ec80-3677-11eb-983b-38ac01e31fd8.png)

You may need to convert ALL instances of default import to the named import in your app, I am not positive about this.

Please let me know if you require more assistance. Otherwise I will close this issue. :rocket:

**Comment by jpribyl** [comment]
@sbondaryev actually, I believe I have a better fix. Update to the latest version of the package. Then, continue to use the DEFAULT export exactly as you have been. However, at the top level of your app include something like this:
```typescript
const mathjaxOptions = {
  loader: { load: ['[tex]/color'] },
  tex: { packages: { '[+]': ['color'] } },
};

ReactDOM.render(
  <>
    <MathJaxProvider options={mathjaxOptions} />
    <App />
  </>,
  document.getElementById('root'),
);
```
This will ensure that mathjax is loaded with the appropriate options. I wrote the package in a way where mathjax will only be loaded once per app.. so you should be free to use color anywhere in the app as long as it occurs after the provider block!

**Comment by sbondaryev** [comment]
@jpribyl I've tested your solution - it works for me. Thank you!
